# Generated by Django 3.0.8 on 2020-09-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.DecimalField(decimal_places=4, max_digits=6)),
                ('humedad', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),


    ]