# Generated by Django 3.0.8 on 2020-09-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensores',
            name='temperatura',
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
    ]
