# Generated by Django 3.0.8 on 2020-09-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0003_auto_20200926_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensores',
            name='temperatura',
            field=models.FloatField(),
        ),
    ]
