# Generated by Django 3.0.8 on 2020-09-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0005_auto_20200926_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensores',
            name='peso',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='sensores',
            name='temperatura',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
    ]
